CREATE TABLE IF NOT EXISTS meta.source_registry_local ON CLUSTER 'osint_cluster_2s2r'
(
    source_id String,
    domain String,
    domain_family LowCardinality(String),
    source_class LowCardinality(String),
    entrypoints Array(String),
    auth_mode LowCardinality(String),
    auth_config_json String,
    format_hint LowCardinality(String),
    robots_policy LowCardinality(String),
    refresh_strategy LowCardinality(String),
    requests_per_minute UInt32,
    burst_size UInt16,
    license String,
    terms_url String,
    attribution_required UInt8,
    geo_scope LowCardinality(String),
    retention_class LowCardinality(String),
    priority UInt16,
    parser_id String,
    entity_types Array(String),
    expected_place_types Array(String),
    supports_historical UInt8,
    supports_delta UInt8,
    backfill_priority UInt16,
    confidence_baseline Float32,
    enabled UInt8,
    disabled_reason Nullable(String),
    disabled_at Nullable(DateTime64(3, 'UTC')),
    disabled_by Nullable(String),
    review_status LowCardinality(String),
    review_notes String,
    schema_version UInt32,
    version UInt64,
    record_version UInt64,
    api_contract_version UInt32,
    attrs String,
    evidence String,
    updated_at DateTime64(3, 'UTC')
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/osint_cluster_2s2r/{database}/{table}/{shard}', '{replica}', record_version)
ORDER BY (source_id);
